name: Push and deploy both services

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.LOCAL_AXLE_425708_T0 }}'
      - name: Set up gcloud project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: local-axle-425708-t0
          install_components: 'beta'
      - name: Push and deploy Label Owner Service
        run: ./label-owner-service/push_and_deploy.sh
      - name: Push and deploy Main Owner Service
        run: ./main-owner-service/push_and_deploy.sh
